services:
  web:
    build:
      context: .
    container_name: pos-wellness-site
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: "Rede Proxy"
